Add FlowStepperIndexedByKey
LedgerHQ/ui pull request #166
Opened 2022-01-27 16:26 UTC by ofreyssinet-ledger

**TL;DR**: Wrapper around the FlowStepper to set active step by a prop `activeKey: string` where each children has their own `itemKey: string` prop.

This allows for usages with a lot of steps where dealing with indices could be
painful and error prone (for instance inserting/removing a step somewhere would shift
the indices of the following steps and navigation would be impacted).

By using string identifiers (`itemKey`) for each step, it's more "human readable"
and less error prone to setup a navigation logic between steps.

https://user-images.githubusercontent.com/91890529/151400255-9fd75b3c-3869-403a-a417-67660e97d884.mov

2022-01-27 18:49 UTC, ofreyssinet-ledger commented on packages/react/src/components/navigation/FlowStepper/index.tsx
> +    header && Array.isArray(header)
there is certainly a better way to do this

2022-01-28 08:26 UTC, LFBarreto requested changes

2022-01-28 08:26 UTC, LFBarreto commented on packages/react/src/components/navigation/FlowStepper/index.tsx
> +  header?: ((props: InnerProps & ExtraProps) => React.ReactNode) | StepExtra[];
i dont really like those mixed types especially when one is an array and the other not :thinking: 
it forces you to check for types all along the component.
i would suggest in those cases splitting this field in 2 seperate ones 
```js
header?: ((props: InnerProps & ExtraProps) => React.ReactNode);
stepHeaders?: StepExtra[];

...

const headerContents = header || stepHeaders.find(...);
...
```

2022-01-28 08:26 UTC, LFBarreto commented on packages/react/src/components/navigation/FlowStepper/index.tsx
> +  footer?: ((props: InnerProps & ExtraProps) => React.ReactNode) | StepExtra[];
same issue here

2022-01-28 08:26 UTC, LFBarreto commented on packages/react/src/components/navigation/FlowStepper/index.tsx
> +  header?: ((props: InnerProps & ExtraProps) => React.ReactNode) | StepExtra[];
or only use a list and check on length :shrug:  to not have to mix types

2022-01-28 09:30 UTC, elbywan reviewed
> 1. FlowStepper.Indexed

I really like this part 👍 💯!

> 2. Add more possibilities for header & footer rendering

I'm wondering instead of making `header` and `footer` potential arrays, how about adding them as props in the `Step` component directly so we can associate the header, footer and the contents of the step in a single place? 

We could make it so that if the `Step` contains a header/footer prop it would override the one from the stepper component, and IMO it would be easier to use than passing arrays (with potentially undefined elements if we want a custom footer/header for a single step for instance).

2022-01-28 10:20 UTC, ofreyssinet-ledger commented
> We could make it so that if the Step contains a header/footer prop it would override the one from the stepper component, and IMO it would be easier to use than passing arrays (with potentially undefined elements if we want a custom footer/header for a single step for instance).

@elbywan very good point yeah i thought about the general idea but didn't really know how to do that. Let me see I'm gonna give it a try now 👍

2022-01-28 15:17 UTC, elbywan approved these changes
Nice work!! 👍 

I was just wondering if you could add something in the existing storybook markdown to document the new features?

2022-01-31 14:31 UTC, merged