LLD - New componennt
LedgerHQ/ui pull request #72
Opened 2021-11-08 13:36 UTC by nparigi-ledger

New:
Tips
![image](https://user-images.githubusercontent.com/89014981/140751327-f100a47f-3abf-4cb2-bb57-e631ff246e5d.png)

Documentation for a simple side drawer

Fixes:

Text

2021-11-09 14:14 UTC, LFBarreto approved these changes

2021-11-09 16:53 UTC, qd-qd requested changes

2021-11-09 16:53 UTC, qd-qd commented on packages/react/src/components/layout/Box/Box.stories.tsx
> +const Square = styled.div<any>`
Yeah, even if it's a story I think we should avoid using `any`

2021-11-17 15:21 UTC, nparigi-ledger commented
@gsoares-ledger Renamed "SideDrawer" to "Drawer" and exported it as an "official" component

2021-11-18 10:55 UTC, merged